openapi: "3.0.3"
info:
  title: "API Title"
  version: "1.0"
tags:
  - name: Orders
components:
  schemas:
    Order:
      type: object
      required:
        - email
        - product
        - quantity
        - totalPrice
      properties:
        _id:
          type: string
          example: "648b45f5e1234b56789a6789"
        email:
          type: string
          example: "customer@example.com"
        product:
          type: string
          example: "648a45e5f0123c45678d9012"
        quantity:
          type: integer
          example: 2
        totalPrice:
          type: number
          example: 36
        createdAt:
          type: string
          example: "2024-11-19T10:23:45.123Z"
        updatedAt:
          type: string
          example: "2024-11-19T10:23:45.123Z"
paths:
  /api/orders:
    post:
      tags:
        - Orders
      requestBody:
        description: Order data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product created successfully"
                  status:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/Order"
        "500":
          description: Order creation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Order creation failed"
                  status:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "ValidationError"
                  stack:
                    type: string
                    example: "Error: Something went wrong\n    at app.js:23:13\n    at..."
  /api/orders/revenue:
    get:
      tags:
        - Orders
      parameters: []
      responses:
        "200":
          description: Revenue calculated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Revenue calculated successfully"
                  status:
                    type: boolean
                    example: true
                  data:
                    properties:
                      totalRevenue:
                        type: number
                        example: 720
        "500":
          description: Revenue calculation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Revenue calculation failed"
                  status:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Revenue calculation failed"
                  stack:
                    type: string
                    example: "Error: Something went wrong\n    at app.js:23:13\n    at..."
